export const generalText = ` Lorem ipsum  sit amet, consectetur adipiscing elit. Praesent rutrum turpis sed orci finibus, eget suscipit nisi consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean a neque placerat, aliquam odio eu, hendrerit augue. Aenean tincidunt egestas mi, vel dictum sapien tincidunt at. Cras laoreet diam ante, eget maximus lectus tincidunt id. Sed lacinia libero dolor, sit amet ultrices erat vehicula id. Sed id congue libero, at suscipit mauris. Ut non nisl in nisi dignissim dapibus. Pellentesque in ex congue, elementum magna quis, ornare lectus. Mauris lacus orci, dignissim sed enim nec, imperdiet mattis risus. Donec dictum arcu et augue luctus condimentum. Donec lobortis sapien ut neque convallis euismod ac eu sem. Cras id lacinia quam. Sed sodales magna ac interdum tincidunt. Praesent sed faucibus sapien. Donec faucibus non felis ac sollicitudin.

Donec molestie eu massa a semper. Integer sit amet nisl porttitor, ultrices turpis id, suscipit elit. Suspendisse laoreet eget magna sed posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec sit amet dictum sem. Aliquam in turpis nec justo vestibulum bibendum eget eget est. Etiam bibendum orci vitae elementum facilisis. Donec blandit justo eu tristique molestie. Integer iaculis, enim a finibus efficitur, turpis felis interdum metus, sit amet ultricies magna mauris id dui. Nunc fermentum velit id sagittis hendrerit. Maecenas luctus tortor eu mi efficitur, rutrum convallis libero luctus. Cras maximus vestibulum velit, in viverra augue iaculis ullamcorper. Vestibulum laoreet leo eget mi convallis, nec faucibus diam cursus. Curabitur lacus turpis, fringilla sed mattis in, ornare vitae quam. Mauris quis justo elementum, rhoncus neque ac, lobortis nunc.

Ut condimentum erat lacus, sit amet tristique orci tempus quis. Mauris sagittis nisl urna, vel iaculis massa eleifend non. Maecenas sit amet sodales lectus, quis tincidunt turpis. Suspendisse semper lacus non nunc rutrum mattis. Nunc tempor condimentum dolor aliquet luctus. Vivamus quis bibendum eros. Aenean efficitur facilisis mauris ac pellentesque. Nam vel molestie sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam et massa rhoncus, egestas elit a, iaculis tellus. Aliquam quis efficitur eros. Praesent nec sollicitudin ex, et aliquam ipsum.

Maecenas pellentesque orci non turpis auctor, quis consequat ex luctus. Nulla accumsan ligula est, et sagittis est malesuada at. Sed vulputate in urna auctor ultricies. Nam porttitor mauris vel metus iaculis, quis scelerisque turpis congue. Integer vitae lacus porttitor, egestas quam et, faucibus ipsum. Donec a justo et sem lobortis finibus ac eu turpis. Aenean rutrum diam quis urna aliquam, sed ornare est fringilla. In id nisl bibendum, facilisis lacus et, rhoncus purus. Maecenas nisl neque, vulputate ac risus at, porttitor dapibus justo. Maecenas in dolor tristique massa pulvinar convallis sit amet quis purus. Cras ac sapien interdum, ultrices arcu eget, bibendum odio. Phasellus placerat vel dui eu lobortis. Sed a viverra lorem. Vivamus arcu velit, eleifend sed egestas eget, tempus nec nisl.

Nullam luctus fringilla eros at auctor. Pellentesque finibus justo risus, ac lacinia tellus scelerisque quis. Proin lectus ipsum, fermentum vel malesuada ut, condimentum rhoncus nibh. Suspendisse sagittis non purus eget luctus. Aliquam venenatis augue porta, viverra dolor et, tempor velit. Nullam ac ligula quis mi congue molestie. Sed ac tortor a ex viverra accumsan. Proin ut purus eget turpis congue vestibulum. Donec sit amet ante augue. Nullam nec aliquam enim.Lorem ipsum  sit amet, consectetur adipiscing elit. Praesent rutrum turpis sed orci finibus, eget suscipit nisi consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean a neque placerat, aliquam odio eu, hendrerit augue. Aenean tincidunt egestas mi, vel dictum sapien tincidunt at. Cras laoreet diam ante, eget maximus lectus tincidunt id. Sed lacinia libero dolor, sit amet ultrices erat vehicula id. Sed id congue libero, at suscipit mauris. Ut non nisl in nisi dignissim dapibus. Pellentesque in ex congue, elementum magna quis, ornare lectus. Mauris lacus orci, dignissim sed enim nec, imperdiet mattis risus. Donec dictum arcu et augue luctus condimentum. Donec lobortis sapien ut neque convallis euismod ac eu sem. Cras id lacinia quam. Sed sodales magna ac interdum tincidunt. Praesent sed faucibus sapien. Donec faucibus non felis ac sollicitudin.

Donec molestie eu massa a semper. Integer sit amet nisl porttitor, ultrices turpis id, suscipit elit. Suspendisse laoreet eget magna sed posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec sit amet dictum sem. Aliquam in turpis nec justo vestibulum bibendum eget eget est. Etiam bibendum orci vitae elementum facilisis. Donec blandit justo eu tristique molestie. Integer iaculis, enim a finibus efficitur, turpis felis interdum metus, sit amet ultricies magna mauris id dui. Nunc fermentum velit id sagittis hendrerit. Maecenas luctus tortor eu mi efficitur, rutrum convallis libero luctus. Cras maximus vestibulum velit, in viverra augue iaculis ullamcorper. Vestibulum laoreet leo eget mi convallis, nec faucibus diam cursus. Curabitur lacus turpis, fringilla sed mattis in, ornare vitae quam. Mauris quis justo elementum, rhoncus neque ac, lobortis nunc.

Ut condimentum erat lacus, sit amet tristique orci tempus quis. Mauris sagittis nisl urna, vel iaculis massa eleifend non. Maecenas sit amet sodales lectus, quis tincidunt turpis. Suspendisse semper lacus non nunc rutrum mattis. Nunc tempor condimentum dolor aliquet luctus. Vivamus quis bibendum eros. Aenean efficitur facilisis mauris ac pellentesque. Nam vel molestie sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam et massa rhoncus, egestas elit a, iaculis tellus. Aliquam quis efficitur eros. Praesent nec sollicitudin ex, et aliquam ipsum.

Maecenas pellentesque orci non turpis auctor, quis consequat ex luctus. Nulla accumsan ligula est, et sagittis est malesuada at. Sed vulputate in urna auctor ultricies. Nam porttitor mauris vel metus iaculis, quis scelerisque turpis congue. Integer vitae lacus porttitor, egestas quam et, faucibus ipsum. Donec a justo et sem lobortis finibus ac eu turpis. Aenean rutrum diam quis urna aliquam, sed ornare est fringilla. In id nisl bibendum, facilisis lacus et, rhoncus purus. Maecenas nisl neque, vulputate ac risus at, porttitor dapibus justo. Maecenas in dolor tristique massa pulvinar convallis sit amet quis purus. Cras ac sapien interdum, ultrices arcu eget, bibendum odio. Phasellus placerat vel dui eu lobortis. Sed a viverra lorem. Vivamus arcu velit, eleifend sed egestas eget, tempus nec nisl.

Nullam luctus fringilla eros at auctor. Pellentesque finibus justo risus, ac lacinia tellus scelerisque quis. Proin lectus ipsum, fermentum vel malesuada ut, condimentum rhoncus nibh. Suspendisse sagittis non purus eget luctus. Aliquam venenatis augue porta, viverra dolor et, tempor velit. Nullam ac ligula quis mi congue molestie. Sed ac tortor a ex viverra accumsan. Proin ut purus eget turpis congue vestibulum. Donec sit amet ante augue. Nullam nec aliquam enim.`;


